modality_paths:
  - D:\Projekty\common-lang\datasets\acc_phone_clip
  - D:\Projekty\common-lang\datasets\gyro_clip

runs_path: D:\Projekty\common-lang\runs

splits:
  preserve_perc: 0.4
  max_modalities_to_drop: 1
  modality_drop_perc: 0.2
